"""empty message

Revision ID: aa21fcfd003a
Revises: 
Create Date: 2017-04-27 02:56:08.497400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa21fcfd003a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test101')
    op.add_column('item', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'user_id')
    op.create_table('test101',
    sa.Column('meme', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
